### ISSUE TITLE
SA-MP skins

### ISSUE THREAD

**Issue by lopezloo** [Kewka/sa-skins#2]
This application may be confusing for non SA-MP users because it includes SA-MP only skins. I think it would be cool if there were two seperate skin lists. One with single player skins and one with SA-MP skins, or even third one with MTA:SA only skins.

MTA:SA skins are documented here:
https://wiki.multitheftauto.com/wiki/Character_Skins
https://wiki.multitheftauto.com/wiki/All_Skins_Page
(these are same models as in single player but some IDs are different)

**Comment by kewka** [comment]
I've added MTA skins. Check out https://sa-skins.netlify.app/mta
Thanks for your feedback!
